name: propertylistserialization
description: iOS compatible plist serialization and deserialization library for Dart.
version: 1.1.1
homepage: https://github.com/electricbolt/dartpropertylistserialization

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  convert: ^3.0.2
  xml: ^6.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.3
